### ISSUE TITLE
NameError: name 'name2codepoint' is not defined

### ISSUE THREAD

**Issue by kenorb** [mycognitive/xgoogle#16]
```
Downloading 'b'somefile'' from 'b'http://www.example.com/somefile'' into ....
Error: Reading socket timed out, try again later.

Traceback (most recent call last):
  File "google_dl", line 161, in <module>
    for results in page:
  File "google_dl", line 79, in __next__
    results = self.gs.get_results()
  File "~/.python/xgoogle/search.py", line 201, in get_results
    results = self._extract_results(page)
  File "~/.python/xgoogle/search.py", line 288, in _extract_results
    eres = self._extract_result(result)
  File "~/.python/xgoogle/search.py", line 295, in _extract_result
    title, url = self._extract_title_url(result)
  File "~/.python/xgoogle/search.py", line 309, in _extract_title_url
    title = self._html_unescape(title)
  File "~/.python/xgoogle/search.py", line 369, in _html_unescape
    return re.sub(r'&([^;]+);', entity_replacer, s, re.U)
  File "~/anaconda/lib/python3.6/re.py", line 191, in sub
    return _compile(pattern, flags).sub(repl, string, count)
  File "~/.python/xgoogle/search.py", line 356, in entity_replacer
    if entity in name2codepoint:
NameError: name 'name2codepoint' is not defined
```

Example command using [`google_dl` utility](https://github.com/mycognitive/google_dl/issues/12):

    google_dl -s http://www.marquette.edu/maqom/ -f pdf ""

**Comment by PrisonGlobe** [comment]
name2code is a local variable there for doesn't exist outside of your function.

**Comment by kenorb** [comment]
It's module and it used in different parts as well, e.g.

```
$ grep -R name2codepoint .
./BeautifulSoup.py:  from htmlentitydefs import name2codepoint
./BeautifulSoup.py:  name2codepoint = {}
./BeautifulSoup.py:        if self.convertHTMLEntities and x in name2codepoint:
./BeautifulSoup.py:            return unichr(name2codepoint[x])
./BeautifulSoup.py:                data = unichr(name2codepoint[ref])
./googlesets.py:from htmlentitydefs import name2codepoint
./realtime.py:from htmlentitydefs import name2codepoint
./realtime.py:            if entity in name2codepoint:
./realtime.py:                return unichr(name2codepoint[entity])
./search.py:            if entity in name2codepoint:
./search.py:                return unichr(name2codepoint[entity])
./search.py:            if entity in name2codepoint:
./search.py:                return unichr(name2codepoint[entity])
./search.py:            if entity in name2codepoint:
./search.py:                return unichr(name2codepoint[entity])
./search.py:            if entity in name2codepoint:
./search.py:                return unichr(name2codepoint[entity])
./sponsoredlinks.py:from htmlentitydefs import name2codepoint
./sponsoredlinks.py:            if entity in name2codepoint:
./sponsoredlinks.py:                return unichr(name2codepoint[entity])
```

What is your suggestion then?
